# Generated by Django 6.0.1 on 2026-02-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фото')),
                ('profession', models.CharField(max_length=100, verbose_name='Профессия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Моя информация',
                'verbose_name_plural': 'Моя информация',
            },
        ),
    ]
